### ISSUE TITLE
Wrapping this server in a container and access it from anywhere, not only claude desktop or cursor/windsurf.

### ISSUE THREAD

**Issue by RonB** [dstotijn/mcp-cbs-cijfers-open-data#1]
Hi David,

I am very intersted in this project because i am working on a platform for ai multi-agent workflows based on langgraph. I know there are many solutions out there, just not with a robust infrastructure and proper backend with authentication, simple flow builder and high scalability.

The platform is rather big with a cloudflare frontend, an api / hub and celery worker containers.
One of the easy ways to access mcp tools is creating docker containers that can connect via sse. stdio is not feasible for mcp-clients/tools attached to agents in langgraph. Therefore i use a simple trick to spin up an mcp-server like so in my docker-compose:

```yaml

  ######################################################################
  # MCP Finance
  ######################################################################
  mcp-finance:
    image: supercorp/supergateway
    container_name: "${ENVIRONMENT}-mcp-finance"
    working_dir: /app
    command:
      --stdio "npx -y @onori/yfinance-mcp-server" && sh apk add bash
    tty: true
```

I dont think i need the wrapper for your cbs server because it already supprts sse out of the box and so have tried this:

```yaml
  ######################################################################
  # MCP cbs
  ######################################################################
  mcp-cbs:
    image: golang:1.24.2-bookworm
    container_name: "${ENVIRONMENT}-mcp-cbs"
    working_dir: /app
    command: >
      bash -c "go install github.com/dstotijn/mcp-cbs-cijfers-open-data@latest &&
          mcp-cbs-cijfers-open-data --http=${ENVIRONMENT}-mcp-cbs:8080 --stdio=false --sse &&
          exec bash"
    tty: true
```

the server installs,  runs and listens:
```
go: downloading github.com/dstotijn/mcp-cbs-cijfers-open-data v0.2.1
go: downloading github.com/dstotijn/go-mcp v0.1.3
go: downloading github.com/invopop/jsonschema v0.13.0
go: downloading github.com/dstotijn/valtor v0.2.0
go: downloading github.com/wk8/go-ordered-map/v2 v2.1.8
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/bahlo/generic-list-go v0.2.0
CBS API MCP server started, using transports: [sse]
SSE transport endpoint: http://localhost:8080

```

I can now access your mcp server remotely from any mcp-client. 
I started this issue when i couldn't get it to work, but that was because i did not specify the http endpoint. 
(My container runs in docker network and so the name of the container is the endpoint).

Thanks for your effort.
